### ISSUE TITLE
ask if is possible to unban my nickname

### ISSUE THREAD

**Issue by camposvitor98** [CommanderRoot/twitch-tools#100]
Hello guys, I may did a bad thing but with good intention, I created an script to donete bits to some friends of mine that do livestream on twitch, and now I got blocked from a ton of channels that I follow. there is a way to remove my nickname from botlist? 

link of my script
https://codepen.io/camposvitor98/pen/RwevKQP

nickname:
Karlarck

**Comment by CommanderRoot** [comment]
Duplicate of #30 

Your account was added to the list on `2022-08-04` as it was part of one or multiple follow bot raids. Sending bits has nothing to do with it. It's possible that it was compromised back then. Either way it happened I have now removed it from the list
