### ISSUE TITLE
Can you help me to check if other accounts are being compromised?

### ISSUE THREAD

**Issue by anonymouslyfen** [CommanderRoot/twitch-tools#103]
Hi, thank you for helping me. Could you help me check if any other accounts have been compromised as well? I think got one is melio003 as username.

Can you also please help me to check Nadieya14 and Nadi3ya whether it is a bot?

**Comment by CommanderRoot** [comment]
`melio003` was on the list and I have removed it now.
`Nadieya14` and `Nadi3ya` are not on the list
