### ISSUE TITLE
Using HoverZoom+ on Clip List Viewer = CSP violation

### ISSUE THREAD

**Issue by Taizunz** [CommanderRoot/twitch-tools#107]
I'm not entirely sure if I should be reaching out to you about this, or reaching out to the HoverZoom+ folks, so I'm just giving it a shot and asking you to begin with.

The HoverZoom+ browser extension allows me to hover over some media elements on webpages to quickly load and display them in a larger format/zoomed in while I keep my mouse hovered over the element/link. This is especially useful for some video/image links on webpages that don't have the media embedded in any way, as it saves me from having to load up an extra tab to view the media which greatly streamlines my browsing habits.

Unfortunately I'm constantly getting CSP violations in console when attempting to user HoverZoom+ to load clips by hovering over their links in your Clip List Viewer tool.

```Refused to load media from 'https://production.assets.clips.twitchcdn.net/v2/media/OptimisticEndearingPeachKappaPride-uXEVEVoja9I1k1xZ/8676c72e-c07f-4439-a175-ae9df85ffaef/video.mp4?<snipped data>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.```

Is this something you're able to help me with via a small change in your tools/pages code, or is it something I should ask HoverZoom devs to fix in their extension??

**Comment by CommanderRoot** [comment]
That's something I can fix and that fix should be live now. Please let me know if it works or not

**Comment by Taizunz** [comment]
That was quick. It works. Thanks so much!
