### ISSUE TITLE
Bluesky Notifications - Doesn't seem to work with custom domains or a PDS?

### ISSUE THREAD

**Issue by fullStackRacc** [CommanderRoot/twitch-tools#108]
Hello all!

I saw this floating around and it seems really useful, but when I try to add my bluesky account, it says that either the account or password are wrong when I am copying both directly from the site, so there's no chance for a mistake.

Does the program only work with bsky.social domains?

**Comment by CommanderRoot** [comment]
In case anyone else finds this issue. This was indeed caused by a different PDS than the "default" `bsky.social`. Custom PDS support has now been added.
