### ISSUE TITLE
Supporting Twitch Emote Search

### ISSUE THREAD

**Issue by ZeldaZach** [CommanderRoot/twitch-tools#13]
Hey there! The feature extension I'm looking for is a way to search across all Twitch emotes by a tag portion. This would be a re-creation of what TwitchEmotes.com had (ex: [Tweet 1](https://twitter.com/djfluffkins/status/1455633702449418242), [Tweet 2](https://twitter.com/MisterPickleman/status/1431804263844491268), [Tweet 3](https://twitter.com/ximOpti/status/1354184315454689280)). 

This service would not necessarily be a content ID lookup, as your service already supports this functionality in a different area.

While digging through the Twitch API, the [broadcast_id is a requirement](https://dev.twitch.tv/docs/api/reference#get-channel-emotes) to get emotes of channels, so in order to index every possible emote it would take a lot of API calls (429s are lurking...) to populate a data set. It seems your service already has a pretty good grasp of this data, just it might be missing an efficient way to query/load this data in a practical way.

I'm personally interested in a search feature to gain ideas and have a wider view at what other content creators have chosen to use for certain emotes (Ex: Blep, Gasp) in order to spark ideas and creativity. I'm more than open to helping bring this feature up if you'd be interested in having an outside contribution.

**Comment by CommanderRoot** [comment]
I remember this feature and know it was quite useful to find certain type of emotes or get emote ideas based on already existing ones.
You're right that I already have this data as I need to know all existing emotes for my emote content ID tool. Currently this data isn't really in the right format for it to be searched this way but I did a quick test loading it into a mysql db. 
```
SELECT * FROM `emotes` WHERE `token` LIKE '%gasp%'
```
There are currently ~13 million emotes and as the searchable string could be anywhere in the token adding a normal index wouldn't help. Knowing that, a query time of 1 sec or more wasn't really surprising. While such a long query time isn't an issue if you just want to lookup some emotes from time to time, it's an issue if it can be done by the public as it makes overloading the server very easy with just a few queries per second.

Searching on Google results in lots of different options for these kind of searches but all would require additional services (like MongoDB or Elasticsearch). This would mean I would have to run additional software and also run cronjobs to keep the data up to date. Not sure if I want to do that as it sounds like quite a lot of work and resources for such a "small" feature.

**Comment by ZeldaZach** [comment]
I kind of figured the old service used a simple LIKE query, similar to what you proposed, which could explain the rapid delay in response times.

Would you consider making a data dump of the emote list? It's something I would find great use in, and would consider setting up an ES stack if it would benefit the community (and not cost a mini fortune). I found this to be a valuable piece of the Twitch Emote ecosystem, and would love to re-create it if possible.

**Comment by CommanderRoot** [comment]
I did some more testing and implemented a solution I'm happy with in terms of resource usage. You can now search Twitch emotes by token (name) via this tool: [https://twitch-tools.rootonline.de/emotes_search.php](https://twitch-tools.rootonline.de/emotes_search.php)
By default it looks for the search parameter within the token (Contains). If you add `^` to the start it does a "HasPrefix" lookup, meaning the emote has to start with the searched string. If you add `$` at the end it does a "HasSuffix" lookup, meaning the emote has to end with the searched string.
The amount of returned results per search is limited to 10k so for some searches like "gg" for example you will only get a partial result.

**Comment by ZeldaZach** [comment]
Interesting approach, I'm very curious how you were able to manage the query load! Since results are limited to 10k, would pagination make sense for us?

**Comment by CommanderRoot** [comment]
I changed the structure and keep the array in memory. The 10k limit is more to not break clients with loading that many images at once. The server doesn't really care that much about the returned results apart from the little bit more network and memory usage when compiling and sending the json. Pagination wouldn't help on the server and make it even worse as you would have to scan all emotes again on each page request and just filter out the page you want.
Pagination on the client however would make sense. Basically the server would send all results in one go (even if it's more than 10k) and then the client would only display part of it (like 250 or so) and would create "virtual" pages.
The question however is: How many people would actually look through the pages (not just the first few ones).
Either way, having it, even with the 10k limit, would be benefitial for mobile users to keep the HTML dom small. Something to code when I have some spare time.

**Comment by ZeldaZach** [comment]
Agreed on minimizing mobile user impact. Might want to consider a warning on the page indicating extensive bandwidth might be used for generic searches.

If you go the route of virtual pages, having some configuration on how many entities to show per page could be beneficial to the UX, as well as a way to maximize screen real estate so users can see as many (or as few) emotes as they'd like.

Currently, the page is a bit more spread out than I would have expected, which just adds a bit of effort to the scroll factor, but overall it's a minor issue.

**Comment by CommanderRoot** [comment]
I added paging on the server now as you're right that this prevents big json responses. I also updated the design / format of the emotes so that there isn't that much free space anymore.

The only thing that could be added would be the ability to jump to a specific page instead of just "Previous" and "Next". With some searches however returning 1000+ pages this could get cluttered real quick.

**Comment by ZeldaZach** [comment]
Caching the number of pages for common requests (blep, pout, sip, etc) could help alleviate that concern. I'd love to do some data analytics on the names people give emotes and see if there's a common case that can be sped up.

One design issue I noticed was long names don't wrap (attached).
<img width="1440" alt="Screen Shot 2022-06-16 at 2 33 40 PM" src="https://user-images.githubusercontent.com/7460172/174141420-25b9ce4b-bb35-47a6-8be9-83e56aa21ca3.png">

Supporting ~250 emotes per page is (probably) okay, but having it be configurable would be better UX.

**Comment by Infinitay** [comment]
Would you be willing to make the data public? If not, is there any chance you can add the following options to searching:

- isAnimated
- Emote Suffix (ignoring the channel's emote prefix)
- Sort by channel follower count

**Comment by CommanderRoot** [comment]
> Would you be willing to make the data public? If not, is there any chance you can add the following options to searching:
> 
>     * isAnimated
> 
>     * Emote Suffix (ignoring the channel's emote prefix)
> 
>     * Sort by channel follower count

- The data is already publicly available via the [Twitch API](https://dev.twitch.tv/docs/api/reference#get-channel-emotes)
- Sadly there doesn't seem to be an easy way to get the emote prefix. You can't even go by "first uppercase letter" as the prefix can end with a number and the suffix can start with one.
- I currently don't store any channel information in regards to emotes. This makes sorting by any channel attribute impossible

**Comment by Infinitay** [comment]
What about a reverse emote search? Given an emote name or id, it would return all of the emotes associated with the channel the respective emote name/id belongs to?

**Comment by CommanderRoot** [comment]
You can already search emotes by name and once you know the emote prefix you can use that with the "Starts with" option to get all emotes of a channel
