### ISSUE TITLE
Auto-discover twitch extensions that the plugin is not yet aware of

### ISSUE THREAD

**Issue by giff-h** [CommanderRoot/twitch-tools#16]
If a channel uses extensions that are not in its list of known extensions, can they be included in the main list to add to the block/allow lists? When a new extension is released it would be nice to allow it on the channel without having to change from "block unless allowed" to "allow unless blocked".

**Comment by CommanderRoot** [comment]
I regularly scan the Twitch extension store to find new Twitch extensions. This however doesn't find "private" Twitch extensions which are restricted to certain channels and can't be installed by everyone.
I have now released v0.4.0 of the browser extension which checks and automatically reports unknown extensions so I can add them faster on the list.
