### ISSUE TITLE
CommanderRoot blocking users who are not bots

### ISSUE THREAD

**Issue by RuckiusTTV** [CommanderRoot/twitch-tools#17]
Having an issue with CommanderRoot blocking 2 of my viewers regularly, one of whom is a mod.

**Comment by CommanderRoot** [comment]
It's possible that the accounts were previously compromised and used for follow botting. You can use the "report" option to report the accounts as "not bots" or write their names here and I will remove them from the list.

**Comment by RuckiusTTV** [comment]
Thanks for that
