### ISSUE TITLE
[Feature Request] Check Bans

### ISSUE THREAD

**Issue by LeetHaxor** [CommanderRoot/twitch-tools#18]
I looked on the tools site for this, so I might just be blind/clueless, but is it possible to add this feature (check if ban perma or suspension) to the tools site? Like you've done on twitter before:

![dytLOOn](https://user-images.githubusercontent.com/41563895/189507535-0168c845-7001-4b93-8729-d7eeb42e5f71.png)

Thanks

**Comment by CommanderRoot** [comment]
Seeing if the current suspension is a DMCA, temporary TOS or indefinite TOS can easily be checked by just going the to channel page. The "error" message is different depending on the type:

Temporary TOS:
> This channel is temporarily unavailable due to a violation of Twitch's Community Guidelines or Terms of Service.

Indefinity TOS:
> This channel is currently unavailable due to a violation of Twitch's Community Guidelines or Terms of Service.

DMCA:
> Content from this channel has been removed at the request of the copyright holder.

**Comment by LeetHaxor** [comment]
> Seeing if the current suspension is a DMCA, temporary TOS or indefinite TOS can easily be checked by just going the to channel page. The "error" message is different depending on the type:
> 
> Temporary TOS:
> 
> > This channel is temporarily unavailable due to a violation of Twitch's Community Guidelines or Terms of Service.
> 
> Indefinity TOS:
> 
> > This channel is currently unavailable due to a violation of Twitch's Community Guidelines or Terms of Service.
> 
> DMCA:
> 
> > Content from this channel has been removed at the request of the copyright holder.

Thanks brother, also thanks for responding so fast!
