### ISSUE TITLE
Whispers export tool

### ISSUE THREAD

**Issue by rmartin-rp** [CommanderRoot/twitch-tools#19]
I think this is an unique feature that none has and it could be quite amazing to have.

Right now, I'm not able to export all my whispers easily for mainly one single reason:
* When I hide a whisper with an user, I need to remember his username to get back that whisper.

So I envision this feature as it follows:
* Find a way to list all users I ever had a private chat (whisper) with him.
* Iterate throuthg that list and export all private conversations.

Even if the second part is dificult, I think the first part (be aware of all users I ever had a private chat) is something that right know it would help a lot to the community.

**Comment by CommanderRoot** [comment]
The public API has only an endpoint to [send whispers](https://dev.twitch.tv/docs/api/reference#send-whisper) which has lots of limitations, including just not sending a whisper but saying it did. There are no public APIs to read or delete whispers.

This means such a tool would have to be a browser extension or browser script running in Tampermonkey. Only this way you could use the undocumented / unsupported GQL API the normal website uses. Doing that however would be against the Twitch dev agreement.

Looking at the requests the website does, there doesn't seem to be an obvious way to know with which users you whispered when you used the hide feature. These whisper threads are basically hidden until you search for the name again.

Exporting would be doable but as you probably don't do it that often you could use a GDPR request to get Twitch to send you all the stored data of you. This data should include whisper messages.

**Comment by rmartin-rp** [comment]
I see, thanks anyways for the quick answer. Congratulations for your tool. Quite useful :)
