### ISSUE TITLE
HELPME to remove account listed as bot

### ISSUE THREAD

**Issue by jelay28** [CommanderRoot/twitch-tools#20]
Hello, greetings, I would like you to help me get off the list of bots, since some time ago I had a virus that affected my twitch account and therefore they gave me a suspension in it, and that was solved by twitch , but I have already had several cases with different twitch channels where they tell me that I am on this list, could you help me remove it since I am a real person and my channel is growing.

Thanks.

ID JELAY28
CHANNEL TWITCH.TV/JELAY28

**Comment by CommanderRoot** [comment]
Hello,

Glad to hear that you got your account back under control. I have removed it from the known bot list.

**Comment by jelay28** [comment]
thaaaaaaaaaaaaaanks i love so much
