### ISSUE TITLE
Not a Bot! uchihagameplay25

### ISSUE THREAD

**Issue by ToraToraVT** [CommanderRoot/twitch-tools#29]
Hi people of CommanderRoot, i have an issue with a friend account, he is not a bot "uchihagameplay25" if you can check he do regulars streams like a normal people, he didnt know why he appeared like a bot, im trying to help him since his English is worst than mine =P. 

He need to do something to be erased from the bot list?.

PD: Tnks for your hard work, a few month ago i received a 300 bot attack, and your tool help me in a few seconds <3.

Best Regards.

**Comment by CommanderRoot** [comment]
I have removed the account from the known bot list.
For future reference you can also use the "Report" links on the follower list viewer or the following list viewer to report accounts as "bot" or "not a bot".
