### ISSUE TITLE
Twitch Stream Filter is acting up?

### ISSUE THREAD

**Issue by Devin2019chs** [CommanderRoot/twitch-tools#36]
I'm not sure if it's me but the stream filter for Twitch on https://twitch-tools.rootonline.de is malfunctioning. When I try to use the filters, every time I try to go to the next page it won't let me go on the next page. It's keeping me on page one. Also when I try to go on the next page, the page refreshes and it goes right back to its default feature. For example when I try to switch from Low viewers to High viewers to let's say Old accounts to New accounts and I press search, it sets me right back to Low viewers to High viewers.

It just started doing this today. I don't know what's going on.

Do you know what the problem is? Am I doing something wrong? Or is it the website?

Thank you

**Comment by CommanderRoot** [comment]
It wasn't you or anything you did. I made a change a few hours ago which apparently broke some things. I have now made another change and everything should be working again as it did previously.
