### ISSUE TITLE
Confused as to why I keep getting set as a known bot

### ISSUE THREAD

**Issue by Noheals1997** [CommanderRoot/twitch-tools#40]
I keep getting linked as a "known bot" on my IRL friends twitch. It is rather annoying and I am pretty sure I am getting marked on others as well. How can I fix this? She has reported me as not a bot multiple times. Why does this keep happening? Is there a way I can keep it from happening?

**Comment by CommanderRoot** [comment]
What's your Twitch account? If it's "NoHeals1997" then that account was added to the list on 2022-07-30. As far as I can tell it was never reported as "not a bot". Either way I have now removed it from the list.

**Comment by Noheals1997** [comment]
It is Noheals1997

Rebecca Vance

On Mar 26, 2023, at 23:02, CommanderRoot ***@***.***> wrote:

﻿

What's your Twitch account?

**Comment by Noheals1997** [comment]
Thanks!

Rebecca Vance

On Mar 27, 2023, at 18:23, CommanderRoot ***@***.***> wrote:

﻿

Closed #40<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCommanderRoot%2Ftwitch-tools%2Fissues%2F40&data=05%7C01%7C%7Cd4cb76202ed049168c0208db2f2afe55%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638155633921281766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QUb%2F55qM%2B%2BscgDpl%2BscXTVWlQ2FtnKDpIIWrcHDXaaU%3D&reserved=0> as completed.
