### ISSUE TITLE
I don't want to be tracked.

### ISSUE THREAD

**Issue by Waspoppin1** [CommanderRoot/twitch-tools#41]
Hello,
Someone on Twitch is using your site to track my account wherever i follow and harass me.How can i make my account untrackable on Following list viewer, please? there should be a method where you could log in with your twitch and then opt-out on that particular thing so others can't see what channels do you follow.
Regards.

**Comment by CommanderRoot** [comment]
The tool only uses the official Twitch API to display this data. So even if my tool would not display it there is nothing preventing someone to use another tool or to write something themself to get this information. In other words, there is currently no way to hide who you follow on Twitch.
All that being said, if you tell me your Twitch account I can add it to an exclusion list so it can't be viewed with my tools.

**Comment by Waspoppin1** [comment]
Hello,
How much would it cost to add 50 accounts to that exclusion list?
Kind regard.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by CommanderRoot** [comment]
I'm not asking for money but I will not add "random" accounts to the list. As these 50 accounts are probably not all yours?

**Comment by Waspoppin1** [comment]
They are mine and friends that don't wanna be tracked as well.
------- Original Message -------
