### ISSUE TITLE
im a streamer but flagged as a bot account for all streamers 

### ISSUE THREAD

**Issue by watchingabyss** [CommanderRoot/twitch-tools#45]
request to remove the username - "watchingabyss" from the potential bot list. im a twitch affiliate streamer and this has caused me problems with other streamers as it unfollowed me and didnt let me follow them back . PLEASE take care of the issue . 

much appreciated.

**Comment by CommanderRoot** [comment]
Duplicate of #30

Your account was added to the list on 2022-09-25 because it was part of a follow bot raid against kurushimuq . I have now removed it from the list

**Comment by watchingabyss** [comment]
Thank you sooooo much !!!
