### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by coinpusherworld** [CommanderRoot/twitch-tools#46]
when searching for twitch emote that is live on twitch its not showing on the site even after a couple of days later. is there away you can get the site to check/update emotes for channels every 2-3hrs

**Comment by CommanderRoot** [comment]
The "List emotes per channel" data gets updated every time a channel goes live (with a small delay) and other than that maybe once per week or so. A scan of around 3.3 million accounts takes quite some time. The "Emote Content ID" and "Emote search by name" gets updated once per day based on the cached data from these scans.

**Comment by coinpusherworld** [comment]
this channel https://twitch-tools.rootonline.de/emotes.php?channel_id=32300738 updated a emote 2 days ago and still not showing his new emote https://i.imgur.com/yuJrIDE.png they have also been live aswell

**Comment by CommanderRoot** [comment]
I just checked my logs and seems like the channel you mentioned got last detected as online on 2023-05-18. It's possible that it was live since then but not listed in the Twitch API due to having 0 or 1 viewers.
I have now manually refreshed the channel

**Comment by coinpusherworld** [comment]
Thank you we look forward in using your site like we did with twitchemotes
