### ISSUE TITLE
Ban known bots in addition to just blocking them.

### ISSUE THREAD

**Issue by ChromiaCat** [CommanderRoot/twitch-tools#47]
I haven't found a clear way to do that so if you know how let me know, otherwise treat this as a feature request since blocking won't do much by itself for bots that might land on my stream chat.

**Comment by CommanderRoot** [comment]
This is currently not a feature for multiple reasons. Most "known bot" accounts are only used for follow botting and do not use chat at all. This means you would ban huge amounts of accounts without gaining anything. Banning also has a much lower rate limit than blocking. Blocking already takes a few days and banning would probably take weeks (with the currently ~4 million known bot accounts).
If you blocked the accounts already you can temporarily use follower only mode and the accounts won't be able to chat as they can't follow.

**Comment by ChromiaCat** [comment]
Okie, thanks for the explanation.
