### ISSUE TITLE
Feature request : followers channel points amount and or global uptime 

### ISSUE THREAD

**Issue by VenusAndThird** [CommanderRoot/twitch-tools#48]
Being able to see how many points and or global uptime per viewer on the channel in the followers and remove followers list (and in the filters)

**Comment by CommanderRoot** [comment]
There is no such thing as "global uptime per viewer" on Twitch. As for channel points, there is no public API to fetch this information and even the website only allows the user to check theirs and not the channel owner (or anyone else) to check the users.
