### ISSUE TITLE
See list of all emotes a user has been credited to drawing

### ISSUE THREAD

**Issue by joanna-cc** [CommanderRoot/twitch-tools#50]
hi! I was wondering if I could suggest a feature to be added to commanderroot. I’d love to be able to input a username and see a list of all the emotes that they’re attributed to as the artist. Sort of like a list of emotes that they are credited to if the uploader added them as the artist on twitch. Is something like this possible? Thank you!

**Comment by CommanderRoot** [comment]
This sounds like a great idea for a new feature. Unfortunately Twitch doesn't return the emote attributions via any of their official APIs which turns this impossible.
