### ISSUE TITLE
[Feature] Twitch stream filter - Boolean Tag Search?

### ISSUE THREAD

**Issue by meat384** [CommanderRoot/twitch-tools#51]
Any chance of adding this? Would be great for further filtering, as twitch still only limits to 1 tag search.

**Comment by CommanderRoot** [comment]
The tag system is a total mess and there are currently over 80k tags. The game selector is already causing the most loading time with ~4k different games. Having another selector with 20 times that would just bog everything down.
Overall I'm not a fan of tags and thus have no plan on building anything with them
