### ISSUE TITLE
issue with follower

### ISSUE THREAD

**Issue by Kejinnn** [CommanderRoot/twitch-tools#52]
I unbanned a user but he can't follower the channel, what should I do to make him follower?

**Comment by CommanderRoot** [comment]
You have to unblock him. Banning and blocking are two different things. The easiest way to unblock an account would be to type "/unblock xxx" in chat. It's also possible to use the [blocklist manager](https://twitch-tools.rootonline.de/blocklist_manager.php) or the [Twitch settings](https://www.twitch.tv/settings/security)
