### ISSUE TITLE
[bug] cant type/super delayed typing in textbox for Channel reviews

### ISSUE THREAD

**Issue by ghost** [CommanderRoot/twitch-tools#55]
Service: [Channel preview](https://twitch-tools.rootonline.de/channel_previews.php)
Browser: Firefox Developer version (117.0b2)
Issue: When typing into input form it types like 1 letter then just stops and lags, 

https://github.com/CommanderRoot/twitch-tools/assets/123487875/ded4dfd0-c69c-4123-9954-11066f49adf3

Things i done:
- [x] tested other browsers such as edge and chrome which works fine
- [x] Made sure to test this on firefox normal which worked fine
- [x] tested the website on firefox dev in debug mode and on a fresh profile. issue was still duplicated
- [x] tried reinstalling firefox dev and issue still persists

Im not sure why the issue occured on the firefox dev specifically but it just started happening today.

**Comment by CommanderRoot** [comment]
This select input uses [bootstrap-multiselect](https://github.com/davidstutz/bootstrap-multiselect). There doesn't seem to be any special handling for this Firefox version (or any other for that matter) and as it works normally in any other browser / version it makes me think that this is a Firefox bug and not a website bug.
Let's hope they notice and fix it before it gets released as a public version.
