### ISSUE TITLE
[Feature] Download massive in compressed file my created clips in other channels.

### ISSUE THREAD

**Issue by luci88ct** [CommanderRoot/twitch-tools#56]
Hi!

I wish we could download in a compressed file all the clips we have created from the different streamers and thus have a personal copy. Thank you so much for everything

**Comment by CommanderRoot** [comment]
This is not really easily possible and it would also not make much sense.

First of all you can't ask the Twitch API for Clips created by an account. You can only get them per channel and then filter yourself (which is possible with my [Clip list viewer](https://twitch-tools.rootonline.de/cliplist_viewer.php)). This restriction would mean that to get all the Clips you created the tool would have to scan every channel for every Clip and then filter the ones you created (not feasible).

As for the "compressed file" part. This would require a server component which you tell which Clips should be downloaded and compressed. The server then would have to do the work and after some time you could download the file. As Clips are videos the compression wouldn't really do anything except to bundle them into one file. You wouldn't save any bandwith on your end but the server would have download (from Twitch) and upload (to you).
You can already use browser extensions to easily download multiple Clips at once (see "guide" on the [Clip list viewer](https://twitch-tools.rootonline.de/cliplist_viewer.php) as example).
