### ISSUE TITLE
Subscription data

### ISSUE THREAD

**Issue by PSingletary** [CommanderRoot/twitch-tools#57]
# New tool idea : Subscriptions list

- list of self subscribed channels
- list of gifted subscriptions to channels (i've been getting a lot in last 24 hours)
- list of Mobile Subscriptions (to avoid iOS/Google tax)
- Turbo Subscription
- Expired Subscriptions (i have more than 99+, want to know all)

great context to have:

- who gifted (that way i can get a count, maybe make them VIP in my / other channels)
- expiration dates, twitch isn't forthcoming as they just want you to have rolling subscriptions

**Comment by CommanderRoot** [comment]
The Twitch API is very limited in that regard. As for subscriptions you can only get a channels subscriber list (with the permission of the channel owner) and you can check if a user is subscribed to a specific channel (with user permission).
It's not possible to get a list of all channels a user is subscribed to. There is also no way to get past subscription information like streaks or expired channels etc
The best you can probably do with what's possible with the API is my [subscriber list viewer](https://twitch-tools.rootonline.de/subscriberlist_viewer.php) which lets you load a list of your subscribers and check how many of them have gifted subs and who gifted the subs.
