### ISSUE TITLE
[emotes search][request] allow to filter by non-animated or animated

### ISSUE THREAD

**Issue by freudnim** [CommanderRoot/twitch-tools#59]
It would be useful to have a toggle for animated emotes in emote search. I use this tool for finding emote inspirations so the toggle would be a nice qol change. If the Twitch api doesn't expose this data then I suppose you can determine whether the emote is animated or not via filetype (png/gif).

**Comment by CommanderRoot** [comment]
I have added the ability to filter emotes by animated / static. Not all emotes are categorized yet so it might take a few days until the results are 100% correct (some animated emotes might be displayed as static until then)

**Comment by freudnim** [comment]
thanks for the quick turnaround!!
