### ISSUE TITLE
Ability to show / hide certain account data on table view

### ISSUE THREAD

**Issue by CommanderRoot** [CommanderRoot/twitch-tools#6]
It would be nice if you could toggle columns to be hidden if you're not interested in that data.

**Comment by Pysis868** [comment]
Also additional ones to show, especially that are not included in the default.

This configuration could even be saved local to the client too.

**Comment by CommanderRoot** [comment]
This was implemented and released today
![grafik](https://user-images.githubusercontent.com/4395417/177777908-729ccbf6-28df-470a-b031-f624e850e2e0.png)
