### ISSUE TITLE
request a feature

### ISSUE THREAD

**Issue by zlobens** [CommanderRoot/twitch-tools#60]
https://imgur.com/Kl3bLj3
annoying
does anyone have any solutions, thanks

**Comment by CommanderRoot** [comment]
You can use this [script](https://twitch-tools.rootonline.de/tampermonkey/twitch_skip-content-warnings.user.js) in combination with the [Tampermonkey](https://www.tampermonkey.net/) browser extension to automatically skip content warning confirm windows and to also hide the warning shown in your screenshot.
