### ISSUE TITLE
Stop viewers whos not logged into Twitch from watching streams

### ISSUE THREAD

**Issue by Section9Ryan** [CommanderRoot/twitch-tools#61]
You might call this a bit.....odd

But ever since someone told me that they don't need to be logged in to watch a stream and I kinda take that idea a bit brash because they can still stalk my streaming channel. So, if you don't care. Could you happen to make this idea a thing?

If you can, thank you

**Comment by CommanderRoot** [comment]
This is something Twitch would have to implement as a 3rd party (like me) has no control over who watches a stream.
You could try to request it as a feature like this one [here](https://twitch.uservoice.com/forums/933812-safety/suggestions/36380185-protect-streamers-by-preventing-any-access-to-chan).
