### ISSUE TITLE
help me with a bug please

### ISSUE THREAD

**Issue by XirouFox** [CommanderRoot/twitch-tools#67]
A while ago I had problems with inappropriate reports on my live, and I decided to use commander root to mass ban some groups that I suspected, after the wave of reports stopped I started to unban some people. Unfortunately these people can no longer see my live or follow me due to a bug in the command... I need help

**Comment by CommanderRoot** [comment]
First of all there is nothing you can do to prevent someone from reporting you.
If the users can't follow you then they are blocked. Blocks and bans are two different things. You can manage your blocklist via this [tool](https://twitch-tools.rootonline.de/blocklist_manager.php). For chat bans you can use this [tool](https://twitch-tools.rootonline.de/chatban_manager.php). As chat bans however don't prevent following my guess would be that you want the block one.
