### ISSUE TITLE
Toggle to switch date display between fixed and relative

### ISSUE THREAD

**Issue by CommanderRoot** [CommanderRoot/twitch-tools#7]
Currently nearly all dates or times are displayed as fixed time (2022-05-11 21:28:00). For some the translation between dates and time since might be not that easy so it would be nice to have a setting or toggle to switch the date time display to relative (22 minutes ago)

**Comment by Pysis868** [comment]
I guess, as long as it's not the vague sort of relative time duration display that has become popular lately.  I would always argue more columns, especially when the show/hide feature for them should not be too difficult.

**Comment by CommanderRoot** [comment]
This was implemented and released today.
![grafik](https://user-images.githubusercontent.com/4395417/178111415-95483ad8-00db-4485-8ee1-ba45d8c08625.png)
