### ISSUE TITLE
Removed followers now they can't refollow

### ISSUE THREAD

**Issue by Keisea** [CommanderRoot/twitch-tools#70]
A while back to have a 'fresh' start,

But now said people can't follow back again

Is there a way around this?

**Comment by CommanderRoot** [comment]
Sounds like the accounts are still blocked. You can manage your blocklist with this [tool](https://twitch-tools.rootonline.de/blocklist_manager.php). Once the users are unblocked they will be able to follow again

**Comment by Keisea** [comment]
Noted ! Thank you, I'll check It out right now

**Comment by Keisea** [comment]
It works, thank you !
