### ISSUE TITLE
Loading blocks freezes tab.

### ISSUE THREAD

**Issue by ChromiaCat** [CommanderRoot/twitch-tools#71]
It gets to ~7 and a half million before it breaks.
Before you ask, there's plenty of ram free when this happens so it's not crashing because ram got filled.
I'm using chrome 120.0.6099.111

**Comment by CommanderRoot** [comment]
Chrome has gotten worse and worse the past versions in regards to how it limits ram usage. Even though there might not be crashes or free system ram available it might limit how much ram a tab can use.
I would recommend trying Firefox as I haven't seen any issues there in regards to the tool not working in high block / user count instances

**Comment by ChromiaCat** [comment]
Small update: It seems that it doesn't actually freeze the tab, rather it slows it down a lot. Also it happened at 8.3mil so it seems kinda random-ish. If I let it keep going it manages to load another 100 blocks every minute or two(or more, I didn't bother to measure the time it takes in this state).
I decided before I nuke the tab to start chrome's task manager and would you look at this:
![image](https://github.com/CommanderRoot/twitch-tools/assets/43613021/b350375d-a0b1-4799-b950-98ce2e20ecf3)
While it may seems the tab is hogging the entirety of the CPU, actually only chrome's task manager reports such high usage. Windows' task manager shows only the normal usage the tab's process truly uses (20-25%).

I might try to use Firefox to see if it can get past this and report back if it does.
It's weird for chrome to do this. I had a youtube tab that was using more ram than the twitch tools one but that one was working fine so I guess it's not a ram limit per se but something else.

**Comment by CommanderRoot** [comment]
I have changed the script slightly to reduce some of the memory usage. I haven't run any detailed test but I would guess it could be up to 30 - 35 % less.

**Comment by ChromiaCat** [comment]
> I have changed the script slightly to reduce some of the memory usage. I haven't run any detailed test but I would guess it could be up to 30 - 35 % less.

I'll test that tomorrow and report back as loading the blocks seems to take a few hours.

**Comment by ChromiaCat** [comment]
I don't know what you changed but it got past the point it breaks and as of writing this it started to count down the users left to block.

As for the memory usage it got to ~1.25gb instead of the 1.5gb mentioned above.
I'll go ahead and close this since it seems to be ok for now.

Thanks for the effort you put into these tools <3
