### ISSUE TITLE
My friend can no longer follow me

### ISSUE THREAD

**Issue by dorian50l** [CommanderRoot/twitch-tools#73]
Hello, it's been a few days since I voluntarily blocked my friend "tehoo" with the Blocklist Manager to see what it really did, the problem is that even when unblocking him on the Blocklist Manager he still remains blocked, this happens when he refollows it immediately and automatically reblocks him, can you help me? Thank you !

**Comment by CommanderRoot** [comment]
It's possible that Twitch has kind of an hiccup. You could try to first block the account again, maybe even via the normal site by typing "/block tehoo" in your chat. Then waiting a minute and then unblocking it by typing "/unblock tehoo" in your chat.

This should hopefully fix the hiccup and lets Twitch register that you want that account to be unblocked.
