### ISSUE TITLE
[Request-Feature] Bluesky Social Autopost - Automatic Post on BlueSky Social when starting a Livestream on Twitch

### ISSUE THREAD

**Issue by RiverLlVE** [CommanderRoot/twitch-tools#74]
Hello👋 

I want to Request a new Feature : Bluesky Social Autopost from Twitch to Bluesky Social like the exist Mastodon Notification System what is available so far.

It would be really great if this were possible. 😊

Grettings
RiverLlVE

**Comment by PSingletary** [comment]
@RiverLlVE I used https://atproto.com/blog/create-post & https://github.com/MarshalX/atproto/tree/main/examples to get me there but if you mean a simple interface for those not intimidated by code, I agree.
I know a lot of Twitch Streamers on BlueSky would appreciate a simple tool

**Comment by CommanderRoot** [comment]
This has been build: [https://twitch-tools.rootonline.de/bluesky_notifications.php](https://twitch-tools.rootonline.de/bluesky_notifications.php)
