### ISSUE TITLE
Falsely taged as a bot

### ISSUE THREAD

**Issue by Dzbejnoss** [CommanderRoot/twitch-tools#77]
Hello i been falsely taged as a bot in your application Twitch Tools is there any way to resolve this issue?
Here's my twitch account: https://www.twitch.tv/dzbejnos

**Comment by CommanderRoot** [comment]
Duplicate of #30

Your account was added to the list on 2022-08-17 most likely because it was compromised back then and used for follow botting. Either way it happened I have now removed it from the list
