### ISSUE TITLE
Unable to link Mastodon Account

### ISSUE THREAD

**Issue by 90sCraig** [CommanderRoot/twitch-tools#78]
Hello, when trying to link my mastodon account for mastodon notifications I receive the following error when redirected to my mastodon instance:

`Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
`

I previously had my account linked, but it stopped working and am unable to re-authenticate or delete and re-add.

**Comment by CommanderRoot** [comment]
What's your Mastodon instance?

**Comment by 90sCraig** [comment]
It's my own private instance
https://pb.craignt.com/

**Comment by CommanderRoot** [comment]
I have removed the stored OAuth app for that domain. It should now be possible to recreate it to link the account

**Comment by 90sCraig** [comment]
That did the trick. Thank you!
