### ISSUE TITLE
[followerlist_viewer] Negate filter results

### ISSUE THREAD

**Issue by EchtkPvL** [CommanderRoot/twitch-tools#79]
Would be awesome to negate some filter options (like "Broadcaster type" or "Account type", obviously not the Yes/No)

**Comment by CommanderRoot** [comment]
I've changed the input to allow multiple selections

Old:
![grafik](https://github.com/CommanderRoot/twitch-tools/assets/4395417/70e192e4-8e58-4e64-9b47-e7bd8818c5fa)

New:
![grafik](https://github.com/CommanderRoot/twitch-tools/assets/4395417/25a6226c-55c7-482c-b37f-a83d475f4848)
