### ISSUE TITLE
Feature request: Bulk Monitor/Restrict | unmonitor/unrestrict 

### ISSUE THREAD

**Issue by TecWiz12** [CommanderRoot/twitch-tools#8]
The ability like we have access as mods for the bulk block terms, 
> ability to bulk monitor / restrict / unmonitor & unrestrict multiple accounts

**Comment by CommanderRoot** [comment]
Unfortunately Twitch hasn't added any public APIs for managing the monitoring or restricting of accounts. There are also no APIs which show possible ban evasion.

I'll keep this issue open in case that changes but for now this isn't possible.
