### ISSUE TITLE
Unable to block new bot accounts

### ISSUE THREAD

**Issue by Duskaru** [CommanderRoot/twitch-tools#81]
Unsure if it's an adblocker or firewall, both of which I have disabled in my attempts to fix this problem.

I'm trying to block new bots and it always ends up giving me "Error while getting preset, please try again. (0, timeout, timeout)."

**Comment by CommanderRoot** [comment]
The timeout of this operation is set to 75 seconds. Does this error happen around that amount of seconds or way earlier / later?

**Comment by Duskaru** [comment]
It times out around 75 seconds, actually, yeah.

**Comment by CommanderRoot** [comment]
I have increased the timeout to 150 seconds now. Please let me know if this fixes the issue for you. 75 seconds should normally be enough but it's possible that this is somehow not enough

**Comment by Duskaru** [comment]
That worked perfectly, thank you!

**Comment by CommanderRoot** [comment]
Happy to hear. Must be a pretty slow connection then between you and the server. Either way, it's working now
