### ISSUE TITLE
Bots bypassing block feature

### ISSUE THREAD

**Issue by sabharpy** [CommanderRoot/twitch-tools#82]
So it may be possible that some spambot makers have found a bypass for the block check, or at least so they claim. Might be worth looking into since they're becoming more active with Trans Day of Visibility coming up and Pride Month coming up shortly here in the US.

**Comment by CommanderRoot** [comment]
It's quite possible that if an account is newly registered or has not been used for botting in the past that it's not yet detected and added to the "known bots" list. The best that can be done in that case is to use the [follower list viewer](https://twitch-tools.rootonline.de/followerlist_viewer.php) to report the account as bot
