### ISSUE TITLE
where did the option to exclude people from being removed go

### ISSUE THREAD

**Issue by Atzukeis** [CommanderRoot/twitch-tools#83]
it doesn't give the option to exclude someone from being removed anymore. if that feature was removed it needs to be added back immediately, no reason for it to be removed as it's extremely helpful.

**Comment by CommanderRoot** [comment]
The option is still at the same place and hasn't been moved or removed
![grafik](https://github.com/CommanderRoot/twitch-tools/assets/4395417/e145719e-09a7-45dc-ab88-01077fb5f532)

**Comment by Atzukeis** [comment]
nope
![image_2024-04-01_160906898](https://github.com/CommanderRoot/twitch-tools/assets/165716879/ae564665-a8dc-49d6-b5c9-82dadcaf6942)
