### ISSUE TITLE
following list - mobile site can't scroll to all display options

### ISSUE THREAD

**Issue by h3oCharles** [CommanderRoot/twitch-tools#84]
opened the following list on android to use the twitch app to do unfollows with. sadly i cant select all display thingies. i cant even do the two-fingers-to-scroll gesture. enabling the desktop-site thing doesn't help, either

hmu if some debug info is needed

![Screenshot_20240403-112435](https://github.com/CommanderRoot/twitch-tools/assets/8020330/2c1d3636-a93f-4867-8517-86c9a115cec2)

**Comment by CommanderRoot** [comment]
Just to be clear on what your issue is. The options you see work but you can't scroll down in the options list below "Account type" as it selects the option when trying to scroll down in the list?

**Comment by h3oCharles** [comment]
i can't scroll down on the dropdown with the display options (profile image, username, etc.). so yes, i cant see anything below account type

**Comment by CommanderRoot** [comment]
I could replicate this issue and have now made the scrollbar wider. For some reason it still doesn't want to scroll better but you can click / tab on the lower part of the scroll bar and see the results at the bottom of the list

**Comment by h3oCharles** [comment]
yup, that did it, i can click on the white part of the scrollbar and that does it. now im struggling to actually hit unfollow on the mobile twitch app, but that's not your problem
