### ISSUE TITLE
Im NOT a Bot

### ISSUE THREAD

**Issue by Hoppel800** [CommanderRoot/twitch-tools#86]
Hey can you pls remove me from the Bot-list? 
Im a very nice and not sussy Twitch User.
im Twitchname ist "Hoppel800" thank you!

**Comment by CommanderRoot** [comment]
Duplicate of #30

Your account was added to the list on `2022-06-25` as it was used in one or multiple follow bot raids. It's quite likely that it was compromised back then. Either way it happened I have now removed it from the list
