### ISSUE TITLE
Use tools in channel I'm a moderator in

### ISSUE THREAD

**Issue by landaire** [CommanderRoot/twitch-tools#87]
Is there a way to use the tools -- specifically the chatban manager tool -- to ban users for a channel I'm a moderator in instead of my own account?

**Comment by CommanderRoot** [comment]
![grafik](https://github.com/CommanderRoot/twitch-tools/assets/4395417/6fb6f76f-ddfb-424e-9b2c-06829c5692af)

The Twitch API only allows the broadcaster to see the list of banned users. It's however possible to ban and unban accounts in channels as a moderator, even if you can't see the list of already banned accounts.
I have now modified the script to allow the user to select a channel they want to do the bans or unbans in.

**Comment by landaire** [comment]
@CommanderRoot exactly what I was looking for. Thanks!
