### ISSUE TITLE
Feature Request: Follower List Viewer

### ISSUE THREAD

**Issue by tonsofail** [CommanderRoot/twitch-tools#9]
For the Follower List Viewer, would there be a way to add a limiter prior to attempting to pull the full list of follower. Generally I would only need the last month or so of followers versus the whole list (on channels I moderate) if I am trying to track something down. So add the variables to limit the search at the start vs after you have pulled the full list.

Thank you

**Comment by CommanderRoot** [comment]
This was already kinda possible by using the "abort" button on the loading status area. With it you can stop the loading of the list and display all currently fetched results.
I have now also added the date of the last found follower which should make it easier to stop when you want to without having to guess based of the number of already loaded followers.
![grafik](https://user-images.githubusercontent.com/4395417/169406110-4b1e3f66-cf8c-43cb-a628-203a5436f7d3.png)
