### ISSUE TITLE
Hey can I be Un-Flagged as a bot? 

### ISSUE THREAD

**Issue by SHAHdow35** [CommanderRoot/twitch-tools#92]
![image](https://github.com/CommanderRoot/twitch-tools/assets/151355120/4480b8a2-ecff-47c7-9176-310400600ddc)

**Comment by CommanderRoot** [comment]
Duplicate of #30 

Your account was added to the list on `2022-09-28 ` as it was part of one or multiple follow bot raids. It's quite likely that it was compromised back then.
Either way it happend I have now removed it from the list
