### ISSUE TITLE
Cannot link Mastodon account

### ISSUE THREAD

**Issue by memmam** [CommanderRoot/twitch-tools#96]
Similar to #78, `Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

Instance is [glitch.lgbt](https://glitch.lgbt). This is my first time trying to use the Mastodon notification tool. If the issue is on instance end, please contact EposVox, it's his instance.

**Comment by CommanderRoot** [comment]
I have removed and re-created the oauth client for that instance and it should now be possible to link accounts on this instance. The old one was created in 2022 and it's possible that the instance got reset or removed the old client since then.

**Comment by memmam** [comment]
That fixed it, thank you!
