### ISSUE TITLE
Feature Request : TwitchCon Meetup

### ISSUE THREAD

**Issue by PSingletary** [CommanderRoot/twitch-tools#97]
1. you currently have a [Following List Viewer](https://twitch-tools.rootonline.de/followinglist_viewer.php)
2. you currently have a [Twitch Stream Filter](https://twitch-tools.rootonline.de/channel_previews.php) that can filter on a DJ Program participant

If the DJ Program Filter works on Badge, then a process could be made to get a list of all the people you follow with upcoming TwitchCon badge so you don't miss you favorite Twitch people when attending TwitchCon
 
or it could be simpler "who has same badge as me, that I follow"

**Comment by CommanderRoot** [comment]
I like the idea but sadly it's not as easy as it might seem.
1. Works within the users browser which means it can only use the data available via any of the public Twitch APIs
2. The data which is displayed here is compiled on the server based of public Twitch APIs (for getting the currently live streams) and some other data sources.

Some of these other data sources don't scale that well but still work fine if they just get used every x minutes to generate the online channel list. They wouldn't work if you potionionally try to get the info of millions of followers.

**Comment by PSingletary** [comment]
I meant to state the scope to be narrowed to people being followed, so couldn't the query be:

1. Get my list of badges
2. Get list of accounts I follow
3. Get badges for those accounts

unless you mean that querying a badge is only possible when and account is online?

**Comment by CommanderRoot** [comment]
Querying a users badges is not possible at all.

There are two public Twitch APIs in relation to badges:

- [Get the broadcaster’s list of custom chat badges](https://dev.twitch.tv/docs/api/reference/#get-channel-chat-badges)
- [Get a list of global chat badges](https://dev.twitch.tv/docs/api/reference/#get-global-chat-badges)

**Comment by PSingletary** [comment]
dang
closing enhancement request
